name: Secrets and Variables

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Show repo variable
        run: echo ${{ vars.MY_REPO_VAR }}

      - name: Show repo secret
        run: echo ${{ var.MY_REPO_SECRET }}
