name: Secrets and Variables

on: [workflow_dispatch]

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    env:
      ENV_SECRET: ${{ secrets.MY_ENV_SECRET }}
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Show repo variable
        run: echo ${{ vars.MY_REPO_VAR }}

      - name: Show repo secret
        run: echo ${{ vars.MY_REPO_SECRET }}

      - name: Show env variable
        run: echo ${{ vars.MY_ENV_VAR }}

      - name: Show env secret
        if: ${{ env.ENV_SECRET == 'env_secret' }}
        run: echo ${{ vars.MY_ENV_SECRET }}
