name: 'Continer Action Workflow'

on: [workflow_dispatch]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Run my own container action
        id: greeting-action
        uses: ./.github/actions/container-action
        with:
          name: ${{ github.actor }}

      - name: Output time set in container action
        run: echo "The time in the container was ${{ steps.greeting-action.outputs.time }}"
